[package]
name = "sonos_scrobbler"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
rusty-sonos = "0.1"
